[general]
list_dir = "~/.config/syncuser"
log_file = "~/.local/share/syncuser/syncuser.log"
rsync_bin = "/usr/bin/rsync"
prompt_sudo_passwd = false
dry_run = false
verbose = false
lan_progress = true
show_stats = true

# Optional global rsync excludes (patterns)
exclude = [".git", ".DS_Store", "*.swp"]

[modules.appconfig]
# If omitted, defaults to "appconfig.list"
list = "appconfig.list"
mirror = true
overwrite_if_newer_mtime = true
overwrite_all = true
backup = false
#backup_suffix = ".bak"

[modules.dotfiles]
mirror = false
overwrite_if_newer_mtime = false
overwrite_all = false
backup = false
#backup_suffix = ".bak"
